Get started with GitHub Actions
Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.

Skip this and set up a workflow yourself 

Search workflows
Suggested for this repository
Jekyll using Docker image
By GitHub Actions

Jekyll using Docker image logo
Package a Jekyll site using the jekyll/builder Docker image.

HTML
Publish Node.js Package to GitHub Packages
By GitHub Actions

Publish Node.js Package to GitHub Packages logo
Publishes a Node.js package to GitHub Packages.

JavaScript
Publish Node.js Package
By GitHub Actions

Publish Node.js Package logo
Publishes a Node.js package to npm.

JavaScript
Webpack
By GitHub Actions

Webpack logo
Build a NodeJS project with npm and webpack.

JavaScript
Deno
By GitHub Actions

Deno logo
Test your Deno project
